### ISSUE TITLE
generate error on wrong server type

### ISSUE THREAD

**Issue by lookfirst** [terraform-providers/terraform-provider-scaleway#101]
I accidentally foobar'd the `type` value and that led to an hour of head scratching...

### Terraform Version
```
Terraform v0.11.10
+ provider.cloudflare v1.9.0
+ provider.scaleway v1.7.0
```

### Affected Resource(s)
scaleway_server

### Terraform Configuration Files
```hcl
resource "scaleway_server" "securenode" {
  image = "${data.scaleway_image.ubuntu_bionic_x86_64.id}"
  name = "foo"
  type = "bar"
  provider = "scaleway"
}
```

### Debug Output
Nothing interesting

### Expected Behavior
Show an error stating `type="bar"` is invalid.

### Actual Behavior
Just a really confusing and unhelpful error message...

```
Error: Error running plan: 2 error(s) occurred:

* module.securenode_paris1.output.ip: Resource 'scaleway_server.securenode' does not have attribute 'public_ip' for variable 'scaleway_server.securenode.*.public_ip'
* module.securenode_paris1.cloudflare_record.securenode: 2 error(s) occurred:

* module.securenode_paris1.cloudflare_record.securenode[1]: Resource 'scaleway_server.securenode' does not have attribute 'name' for variable 'scaleway_server.securenode.*.name'
* module.securenode_paris1.cloudflare_record.securenode[0]: Resource 'scaleway_server.securenode' does not have attribute 'name' for variable 'scaleway_server.securenode.*.name'
```

### Steps to Reproduce
1. `terraform plan`

**Comment by nicolai86** [comment]
@lookfirst I’m sorry for the bad experience the error message gave; this definitively needs improvement.

**Comment by lookfirst** [comment]
@nicolai86 No sorry! Just wanted to file it to get it improved. Thanks! =) Love TF!

**Comment by jerome-quere** [comment]
Hi @lookfirst, this resource has been deprecated in favor of `scaleway_instance_server`. The error message should be much cleaner in the new resource.
I going to close this one now.
