### ISSUE TITLE
[Enhancement] Upload ssh key

### ISSUE THREAD

**Issue by sagarafr** [terraform-providers/terraform-provider-scaleway#109]
Hello,
I found a problem during the apply of ssh key, at Scaleway. Indeed, if the file content an end of line, the SSH key is not uploaded. To avoid that, you must strip the ssh key. I propose 2 things to solve the problem :
- Update the documentation and use the following plan :
```hcl
data "local_file" "public_key" {
	filename = "${var.public_key}"
}

resource "scaleway_ssh_key" "public_key" {
	key = "${replace("${data.local_file.public_key.content}", "\n", "")}"
}
```

- Patch the code and strip the end of line

In case of multiple keys, I don't know the behavior.

### Terraform Version
```
$ terraform -v
Terraform v0.11.11
+ provider.scaleway v1.8.0
```

### Affected Resource(s)
- scaleway_ssh_key

### Terraform Configuration Files
provider.tf
```hcl
provider "scaleway" {
	organization = "${var.organization_id}"
	token = "${var.token}"
	region = "${var.region}"
}
```
main.tf
```hcl
resource "scaleway_ssh_key" "public_key" {
      key = "${file("${var.public_key}")}"
}
```
variables.tf
```hcl
variable "organization_id" {
	description = "Your organization id"
	type = "string"
}

variable "token" {
	description = "Your secret key"
	type = "string"
}

variable "region" {
	description = "Desired region (default: ams1)"
	type = "string"
	default = "ams1"
}

variable "public_key" {
	description = "Desired ssh key"
}
```

### Debug Output
Gist : https://gist.github.com/sagarafr/7e06bcf038443e5e097f0be0e8667231

### Expected Behavior
Does not fail

### Actual Behavior
Fail because there are a '\n' at the end of file

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `$ terraform init -var "public_key=~/.ssh/id_rsa.pub" -var "organization_id=org_id" -var "token=token"`
2. `$ terraform plan -var "public_key=~/.ssh/id_rsa.pub" -var "organization_id=org_id" -var "token=token"`
3. `$ terraform apply -var "public_key=~/.ssh/id_rsa.pub" -var "organization_id=org_id" -var "token=token"`

Have a great day

**Comment by nicolai86** [comment]
this will be fixed with the next release thanks to @azuenko
