### ISSUE TITLE
[Enhancement] Support for port ranges on scaleway_security_group_rule

### ISSUE THREAD

**Issue by tmlye** [terraform-providers/terraform-provider-scaleway#120]
It is currently not possible to specify a port range on the scaleway_security_group_rule:
```terraform
resource "scaleway_security_group_rule" "accept_api" {
  security_group = "${scaleway_security_group.kubernetes_node.id}"

  action    = "accept"
  direction = "inbound"
  ip_range  = "0.0.0.0/0"
  protocol  = "TCP"
  port      = "30000-32767"
}
```
The above fails: `Error: scaleway_security_group_rule.accept_api: port: cannot parse '' as int: strconv.ParseInt: parsing "30000-32767": invalid syntax`.

The scaleway API seems to support port ranges, here's the response found in the [documentation](https://developer.scaleway.com/#security-groups-manage-rules):
```json
{
  "rule": {
    "direction": "inbound",
    "protocol": "TCP",
    "ip_range": "0.0.0.0/0",
    "dest_port_from": null,
    "action": "drop",
    "position": 2,
    "dest_port_to": null,
    "editable": null,
    "id": "ef2136c9-6c21-491a-b238-b38de24726a7"
  }
}
```

**Comment by QuentinBrosse** [comment]
Hi @tmlye,
This feature has just been merged in the new [`scaleway_instance_security_group`](https://www.terraform.io/docs/providers/scaleway/r/instance_security_group.html): https://github.com/terraform-providers/terraform-provider-scaleway/pull/358.
It will be available in the next version of the provider, the released is planned for next week.

Thanks for your contribution!
