### ISSUE TITLE
Describe format of .scwrc

### ISSUE THREAD

**Issue by abitrolly** [terraform-providers/terraform-provider-scaleway#121]
#111 added support for `.scwrc` and made it the "recommended" authentication method if no credentials are supplied the other way.
```
✗ terraform plan

Error: Error asking for user input: 1 error(s) occurred:

* provider.scaleway: Error configuring scaleway: organization: error loading default: error loading default: open /home/anatoli/.scwrc: no such file or directory
```
I don't mind setting this file, but could anyone describe the format, please?
```
✗ terraform -v
Terraform v0.11.13
+ provider.scaleway v1.9.2
```

**Comment by QuentinBrosse** [comment]
I will close this issue, you can find the explanation [here](https://github.com/terraform-providers/terraform-provider-scaleway/pull/122#issuecomment-541011287).

Thanks a lot for your contribution ! 👍

**Comment by abitrolly** [comment]
I will test this next time I get back to Scaleway.
