### ISSUE TITLE
Terraform 0.12

### ISSUE THREAD

**Issue by jackivanov** [terraform-providers/terraform-provider-scaleway#124]
Scaleway provider is not compatible with terraform 0.12

### Terraform Version
```
$ ./terraform -v
Terraform v0.12.0-rc1
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 0.12"
}

provider "scaleway" { }
```

### Actual Behavior
> No available provider "scaleway" plugins are compatible with this Terraform version.

### Steps to Reproduce
1. `terraform init`

**Comment by QuentinBrosse** [comment]
Hi,

I already have an issue ready for this: https://github.com/QuentinBrosse/terraform-provider-scaleway/pull/1

We will try to merge it on Monday. :)

**Comment by opichon** [comment]
I am still getting this error: `Error: no available version is compatible with this version of Terraform when running `terragorm init`.

**Comment by QuentinBrosse** [comment]
Hi @opichon, 

Check my answer in #133 :)
