### ISSUE TITLE
Fix all acceptance tests

### ISSUE THREAD

**Issue by QuentinBrosse** [terraform-providers/terraform-provider-scaleway#126]
Two acceptance tests fail, we have to fix them:

- `TestAccScalewayDataSourceImage_Filtered`

```bash
--- FAIL: TestAccScalewayDataSourceImage_Filtered (10.01s)
    testing.go:538: Step 0 error: Error refreshing: 1 error(s) occurred:

        * data.scaleway_image.ubuntu: 1 error(s) occurred:

        * data.scaleway_image.ubuntu: data.scaleway_image.ubuntu: The query returned no result. Please refine your query.
```

- `TestAccScalewayBucket`

```bash
--- FAIL: TestAccScalewayBucket (0.02s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * scaleway_bucket.base: 1 error(s) occurred:

        * scaleway_bucket.base: Only the AMS1 region is supported at the moment
```

**Comment by nicolai86** [comment]
The first error is most likely due to an old image being deleted. My understanding is that the new storage has been rolled out to all regions so the second error should work by now without setting the scaleway region to AMS1.. 
note that the integ tests run with region set to AMS1 today.

**Comment by QuentinBrosse** [comment]
### `TestAccScalewayDataSourceImage_Filtered`
You're right, the `Ubuntu Precise` don't exist anymore. I will update this test to `Ubuntu Bionic`.

### `TestAccScalewayBucket `
I can't find where you set `AMS1` region for tests.

During the `testacc` in [resourceScalewayBucketCreate](https://github.com/terraform-providers/terraform-provider-scaleway/blob/57147ab4e0759f907affffd02c2ed49ff8c29d06/scaleway/resource_bucket.go#L46-L59), `scaleway.Region == "par1"`. I think that if we change [this line](https://github.com/nicolai86/scaleway-sdk/blob/master/api.go#L131) in your SDK `objectstoreAPI`  will be `par1` by default (like `computeAPI`). Therefore, [this condition](https://github.com/nicolai86/scaleway-sdk/blob/master/container.go#L140-L142) should not return the "Only the AMS1 region is supported at the moment" error anymore.

```golang
switch region {
case "par1", "":
	s.computeAPI = ComputeAPIPar1
---	s.objectstoreAPI = ""
+++	s.objectstoreAPI = ObjectStorageAPIPar1 // https://sis-par1.scaleway.com/
case "ams1":
	s.computeAPI = ComputeAPIAms1
	s.objectstoreAPI = ObjectStorageAPIAms1
default:
	return nil, fmt.Errorf("%s isn't a valid region", region)
}
```

What do you think @nicolai86?

**Comment by nicolai86** [comment]
The region is set via the SCALEWAY_REGION environment variable.

The object storage is available in par1 now too, right? In that case we should update the SDK as you suggested.

**Comment by QuentinBrosse** [comment]
Yes but are we agree that by default no region is set in tests so the default region of the SDK (par1) is used?

I will double check internally to be sure but it seems that it available because https://sis-par1.scaleway.com/ is up and running. :) I will keep you informed on Monday.

**Comment by nicolai86** [comment]
Depends: the hashicorp internal CI runs with region set to AMS1 IIRC. But we can ask them to change this once we lift the restriction in the SDK.

**Comment by QuentinBrosse** [comment]
Ok thanks for the precision the Hashicorp internal CI. :)

I've asked internally, the SIS service (actually used by the `scaleway_bucket`) is totally deprecated and replaced by our new [object storage service](https://www.scaleway.com/en/object-storage/). Therefore, we will deprecate the `scaleway_bucket` in the `v1.10.0`. I will add it in the [v2 roadmap](https://github.com/terraform-providers/terraform-provider-scaleway/issues/125) and integrate the [new object storage](https://www.scaleway.com/en/object-storage/) resources.

**Comment by nicolai86** [comment]
Is the migration away from the SIS api a change where customers will need fo migrate their data?

**Comment by QuentinBrosse** [comment]
@nicolai86 No data migrations will be needed and it will be totally seamless for users. The buckets and data are still accessible via the new S3 API. (more info in #130)

**Comment by nicolai86** [comment]
Sweet
