### ISSUE TITLE
Refactor the configuration interface

### ISSUE THREAD

**Issue by QuentinBrosse** [terraform-providers/terraform-provider-scaleway#131]
## The Problem

Until now, the Scaleway terraform provider used the @nicolai86 [Scaleway SDK](https://github.com/nicolai86/scaleway-sdk). I thank the opportunity to thanks him for this great help! 👏

We have just released our new [Go SDK](https://github.com/scaleway/scaleway-sdk-go) and we want to use it in the implementation of future new resources (cf. #125 Step 1 - item 5 and 6).
Moreover, in order to avoid breaking changes during the [Step 1](https://github.com/terraform-providers/terraform-provider-scaleway/issues/125) we want to keep the first version of the SDK for all the deprecated resources.

## What that mean?

We need the two SDKs for the `>= v1.10.0` in a single shared structure. The old SDK will be considered deprecated and therefore will be removed - like any other deprecated elements - in the `v2.0.0`.

For the moment, here is our [configuration interface](https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/vendor/github.com/hashicorp/terraform/helper/schema/provider.go#L71-L74):

```go
// Client contains scaleway api clients
type Client struct {
	scaleway *sdk.API
}
```

We have to rename it into something that is more abstracted - e.g. `Config` - that will contain the SDK clients:

```go
// Meta contains SDK clients used by resources.
//
// This meta value is passed into all resources.
type Meta struct {
        // In near futur: The new Scaleway SDK Client.
	scwClient        *scw.Client
        // In near futur: The AWS S3 Client that will be used for S3 resources.
        // Could be init by an `S3Client` method only when an S3 resource is used.
        s3Client         *s3.S3
        // The deprecated Scaleway SDK (will be removed in `v2.0.0`).
	deprecatedClient *api.API
}
```

**Comment by nicolai86** [comment]
Sounds like a good idea to move to an actively maintained SDK! I like it.
