### ISSUE TITLE
no provider found for terraform 0.12

### ISSUE THREAD

**Issue by opichon** [terraform-providers/terraform-provider-scaleway#133]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "scaleway" {
  organization = "xxx"
  token        = "xxx"
  region       = "par1"
}

resource "scaleway_server" "builder" {
  count = "${var.builder_count}"
  dynamic_ip_required = true
  image = "89c80d27-ddf4-4ffa-8215-b335cce3fd05"
  name  = "${format("builder-%02d", count.index + 1)}"
  type  = "DEV1-S"
}
```

### Expected Behavior
What should have happened?

### Actual Behavior
```$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No available provider "scaleway" plugins are compatible with this Terraform version.
```

### Steps to Reproduce
1. `terraform init`

### Important Factoids
terraform is installed on OSX Mojave using homebrew.

### References
GH-124 refers to the same issue and is maarked as closed, but problem persists for me.

**Comment by lucasff** [comment]
Also happening for me here

**Comment by QuentinBrosse** [comment]
Hi,

The work has been done for the `terraform v0.12` compatibility has been done but we have to release a new version of this provider to allow you to use it. Ha I said [in this comment](https://github.com/terraform-providers/terraform-provider-scaleway/issues/125#issuecomment-497683995) we will release a new minor version next week (we hope it will be possible on monday).

**Comment by QuentinBrosse** [comment]
Hi,

The [v0.10.0](https://github.com/terraform-providers/terraform-provider-scaleway/releases/tag/v1.10.0) is now released! It will fix this issue.
Feel free to reopen it if you encounter any problems.

**Comment by lucasff** [comment]
I ended up using `tfenv` and installing terraform 0.11 to use scaleway and continue using 0.12 for other stuff. That's a good workaround for the moment.

**Comment by QuentinBrosse** [comment]
@lucasff Has I said above, the [v0.10.0](https://github.com/terraform-providers/terraform-provider-scaleway/releases/tag/v1.10.0) is now released! It will fix this issue. So you can now use `v0.12` with our provider. 😄

```bash
$> terraform --version
Terraform v0.12.0

$> cat example.tf
provider "scaleway" {
  region  = "ams1"
  version = "~> 1.10"
}
[...]

$> terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "scaleway" (terraform-providers/scaleway) 1.10.0...

Terraform has been successfully initialized!
```
