### ISSUE TITLE
DEV1-S fail with bad size of attached volume

### ISSUE THREAD

**Issue by julienfr112** [terraform-providers/terraform-provider-scaleway#154]
### Terraform Version

Terraform v0.12.1
+ `provider.scaleway` v1.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `opc_instance` `DEV1-S`

## tarrform .tf

```tf
resource "scaleway_server" "bastion" {
  name  = "bastion${count.index}"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d"
  type  = "DEV1-S"
  volume {
       size_in_gb = 12
       type       = "l_ssd"
  }
  count = 2
}
```

### Debug Output

```bash
Error: StatusCode: 400, Type: invalid_request_error, APIMessage: The total size of local-volume(s) of instances DEV1-S must be equal to 20GB

  on sw.tf line 7, in resource "scaleway_server" "bastion":
   7: resource "scaleway_server" "bastion" {



Error: StatusCode: 400, Type: invalid_request_error, APIMessage: The total size of local-volume(s) of instances DEV1-S must be equal to 20GB

  on sw.tf line 7, in resource "scaleway_server" "bastion":
   7: resource "scaleway_server" "bastion" {
```

**Comment by nicolai86** [comment]
@julienfr112 sorry for the inconvenience.

From my understanding this is expected though as those instances require a 20gb HDD minimum - what happens if you bump 12 to 20?

**Comment by julienfr112** [comment]
still not working, I've tried with no volume, with 20go volume, with -30 volume,, nothing works.

**Comment by QuentinBrosse** [comment]
Hi @julienfr112,

As the error tells: "The total size of local-volume(s) of instances DEV1-S must be equal to 20GB".
The `scaleway_server` resource automatically creates a system volume of 20GB. If specify another volume of 20GB in your configuration, the size total size will be 40GB.

In conclusion, the fix is simple here: just remove the `volume` from your configuration:

```tf
resource "scaleway_server" "bastion" {
  name  = "bastion${count.index}"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d"
  type  = "DEV1-S"
  count = 2
}
```

I will close this issue, do not hesitate to reopen it if you have any question. 🙂

**Comment by kudos** [comment]
Something to note with this error message (I haven't seen it documented anywhere), when using a custom image it seems to be restricted by the volume size of the instance you built it on. For example, I can't boot a `DEV1-S` on an image that was built using a `DEV1-L`.

**Comment by QuentinBrosse** [comment]
Hi @kudos,

It's totally normal. The `DEV1-S` requires a total volume size of exactly `20GB` and the `DEV1-L` requires a total volume size of exactly `80GB`. So your `DEV1-L` volume is too big to be attached to a `DEV1-S` instance. You can find these values [with the API](https://api.scaleway.com/instance/v1/zones/fr-par-1/products/servers). We will improve the documentation to allow you to find the right volume for the right server easily.

The actual `scaleway_server` resource asks the Scaleway API for the optimal system volume size. For the `DEV1-L` it is `80GB` and for `DEV1-S` it is `20GB`. We are working [on a new version](https://github.com/terraform-providers/terraform-provider-scaleway/issues/143) of this resource who will allow you to custom your system volume size. Therefore, you will be able to create `DEV1-L` a system volume of `20GB` with an additional volume of `60GB`. The `20GB` system volume will be compatible with your `DEV1-S`.

**Comment by ASVBPREAUBV** [comment]
is this still an issue?
This worked for me:

```
resource "scaleway_instance_security_group" "www" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    action = "accept"
    port = "22"
  }

}


resource "scaleway_instance_server" "web" {
  type = "DEV1-S"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d"

  tags = [
    "hello",
    "public"]

  root_volume {
    size_in_gb = 20
    delete_on_termination = false
  }


  security_group_id = scaleway_instance_security_group.www.id
}
```

**Comment by QuentinBrosse** [comment]
@ASVBPREAUBV nop, it's not an issue as you use the new `scaleway_instance_server` resource and not the deprecated one: `scaleway_server`. :)

(Note that you can use `image = "ubuntu-bionic"` instead of the local image UUID. Here is [the doc](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html#image)).
