### ISSUE TITLE
Server type inconsistent: "VC1S" => "X64-2GB"

### ISSUE THREAD

**Issue by harobed** [terraform-providers/terraform-provider-scaleway#17]
When I look the `--commercial-type` list, I see:

```
$ scw create --help
...
  --commercial-type=X64-2GB Create a server with specific commercial-type C1, C2[S|M|L], X64-[2|4|8|15|30|60|120]GB, ARM64-[2|4|8]GB
```

I use `X64-2GB` server type in my terraform config file:

```
resource "scaleway_server" "myserver" {
  name = "myserver"
  image = "a869957c-6e1a-4b99-bc07-0748aa42c616"
  type = "VC1S"
}
```

After `terraform apply` execution, if I launch `terraform plan` I have:

```
Terraform will perform the following actions:

-/+ scaleway_server.monitor1 (new resource required)
      id:           "321ab554-7c16-447d-ac3a-db06f82aa04f" => <computed>
      enable_ipv6:  "false" => "false"
      image:        "a869957c-6e1a-4b99-bc07-0748aa42c616" => "a869957c-6e1a-4b99-bc07-0748aa42c616"
      name:         "myserver" => "myserver"
      ...
      state_detail: "booted" => <computed>
      type:         "VC1S" => "X64-2GB"

Plan: 1 to add, 0 to change, 1 to destroy.
```

*terraform* read `VC1S` and not `X64-2GB` then it want always destroy the server.

Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by nicolai86** [comment]
@harobed thank you for the report. 

Smaller X64 instance types are called `Cxy` or `VCxy`. The smallest `X64` instance type is `X64-15GB`. Misleadingly, the Scaleway API accepts `X64-2GB` and creates a `VC1S` instead. This is where your bug report comes in.
However, the Scaleway provider should validate that the instance type is as desired, because the transformation is misleading.

See this for a working `X64-15GB` instance type:

```
provider "scaleway" {}

data "scaleway_image" "ubuntu" {
  architecture = "x86_64"
  name         = "Ubuntu Zesty"
}

resource "scaleway_server" "base" {
  name  = "test"
  image = "${data.scaleway_image.ubuntu.id}"
  type  = "X64-15GB"

  volume {
    size_in_gb = 150
    type       = "l_ssd"
  }
}
```

I will keep this bug report open as a reminder to implement commercial type validation as part of the provider.

**Comment by nicolai86** [comment]
I've just checked the Scaleway API, the best way to date would be to consume server availability via `https://availability.scaleway.com/availability.json` and extract the valid server types from that API call. This way we're on the safe side when Scaleway decides to add new server types.

I still need to investigate how to best do this in an attribute validation callback inside terraform.

**Comment by nicolai86** [comment]
The SDK has been updated - I hope to be able to extend the SDK over thanksgiving to validate server types. I'll let you know how it goes :)
