### ISSUE TITLE
Some Instances fail to start 

### ISSUE THREAD

**Issue by silkysulky** [terraform-providers/terraform-provider-scaleway#198]
Hi

I have a terraform script with 4 modules (one is a security_group) to stand up 9 instances on scaleway using 3 different images. Using Terraform 0.11 & Scaleway Provider 1.9.2 everything stands up as it should with all instances starting and terraform reporting apply is complete.

If I try and use Terraform 0.12 & Scaleway Provider 1.10 between 1 and 4 instances fail to start. I have tried 10+ times and consistently end up with the same result. There is no consistency however in which instances don't start in terms of the 3 different server types, one attempt might have 1 instance type not start and another have 2, then when I try again it will be a different set of instances.

I understand from Scaleway that after an instance is created that a "start" command needs to be sent to the API for each instance, is it possible that the current provider version isn't doing that correctly or too fast if the instance is created more slowly? I have asked them for logs from their side to see what happens when I run the script but I haven't got anywhere with that yet.

### Terraform Version
`0.12 / Scaleway Provider 1.10`

### Affected Resource(s)
`servers`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "commercial_type" {
  default = "DEV1-S"
}

variable "architectures" {
  default = {
	DEV1-S = "x86_64"
      }
}

provider "scaleway" {
  	region       = "par1"
}

module "security_group" {
  source = "./modules/security_group"
}

module "consul_server" {
  source = "./modules/consul_server"

  security_group = "${module.security_group.id}"
  
  type  = "${var.commercial_type}"
  image = "dee0e53a-5486-415a-94d6-7bfdce826232"
}

module "nomad_server" {
  source            = "./modules/nomad_server"
  security_group    = "${module.security_group.id}"

  type  = "${var.commercial_type}"
  image = "960af157-67a3-4c02-9ac1-a84329f35f06"
}

module "consul_nomad_client" {
  source = "./modules/consul_nomad_client"

  security_group = "${module.security_group.id}"
  
  type  = "${var.commercial_type}"
  image = "77e2e4a2-7bba-4349-bf45-f185149461fc"
}

### Module Config File (all 3 module files are the same apart from which image they use and names)

variable "server_count" {
  default     = "3"
  description = "The number of Consul & Nomad Clients servers to launch."
}

variable "image" {}

variable "type" {
  default     = "x86_64"
  description = "Scaleway Instance type."
}

variable "security_group" {
  description = "Security Group to place servers in"
}


resource "scaleway_server" "server" {
  count = "${var.server_count}"
  name  = "nomad-consul-client-${count.index + 1}"
  image = "${var.image}"
  type  = "${var.type}"
  security_group = "${var.security_group}"
  dynamic_ip_required = false
  enable_ipv6 = false
  tags = ["Rule9consul"]  
}
```

### Debug Output
No specific debug info, terraform will continue to run waiting for the instances to start so never completes. 

### Expected Behavior
All instances should start

### Actual Behavior
1-4 instances fail to start and remain in `archived` mode

### Steps to Reproduce

1. `terraform apply`

**Comment by kindermoumoute** [comment]
Hi @silkysulky when did this happen? Does it happen consistently over time?

I couldn't reproduce your issue yet, starting 10 servers in // worked. But I suspect the issue comes from the API not terraform. Can you show your quotas?
```
curl -H "X-Auth-Token: $TOKEN" -L account.scaleway.com/organizations/$ORG_ID/quotas
```

**Comment by silkysulky** [comment]
Hi @kindermoumoute I tested Terraform 0.12 for the first time Tuesday. It happens every time I try to create this 9 instance cluster. Terraform 0.11 works every time without fail. I ran a test of Applying & Destroying 10 times. 100% success with 0.11. 0% success with 0.12. I have to manually destroy the instances via the console as the TF state isn't completed as Terraform would run forever waiting for the instances which don't start to start.

I have a quota of 40 for the instance type I am using in this script, so plenty of head room to spin up 9 instances as I don't have any others of them running.

**Comment by QuentinBrosse** [comment]
I can't reproduce your bug:

**Comment by QuentinBrosse** [comment]
Hi @silkysulky, I can't reproduce your bug:

```bash
$ terraform --version
Terraform v0.12.3 # << .3
+ provider.scaleway v1.10.0

$ tree
.
├── modules
│   └── consul
│       └── main.tf
└── test.tf
```

Simplified consul module:

```tf
# modules/consul/main.tf
variable "server_count" {
  default     = "3"
  description = "The number of Consul & Nomad Clients servers to launch."
}

variable "image" {}

variable "type" {
  default     = "DEV1-S" # not that "x86_64" is an invalid type
  description = "Scaleway server commercial type."
}

variable "name" {
  description = "Server name used as prefix"
}

resource "scaleway_server" "server" {
  count               = "${var.server_count}"
  name                = "${var.name}-${count.index + 1}"
  image               = "${var.image}"
  type                = "${var.type}"
  dynamic_ip_required = false
  enable_ipv6         = false
  tags                = ["Rule9consul"]
}
```

Simplified root module

```tf
variable "commercial_type" {
  default = "DEV1-S"
}

provider "scaleway" {
  region = "par1"
}

module "consul_server" {
  source = "./modules/consul"

  name = "consul-server"
  type = "${var.commercial_type}"
  # image = "dee0e53a-5486-415a-94d6-7bfdce826232"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d" # ubuntu
}

module "nomad_server" {
  source = "./modules/consul"

  name = "nomad-server"
  type = "${var.commercial_type}"

  # image = "960af157-67a3-4c02-9ac1-a84329f35f06"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d" # ubuntu
}

module "consul_nomad_client" {
  source = "./modules/consul"

  name = "consul-nomad-client"
  type = "${var.commercial_type}"

  # image = "77e2e4a2-7bba-4349-bf45-f185149461fc"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d" # ubuntu
}
```



Try:

```bash
$ terraform apply

[...]

Plan: 9 to add, 0 to change, 0 to destroy.

[...]

module.consul_server.scaleway_server.server[0]: Creating...
module.consul_nomad_client.scaleway_server.server[0]: Creating...
module.consul_server.scaleway_server.server[1]: Creating...
module.consul_nomad_client.scaleway_server.server[1]: Creating...
module.consul_nomad_client.scaleway_server.server[2]: Creating...
module.consul_server.scaleway_server.server[2]: Creating...
module.nomad_server.scaleway_server.server[2]: Creating...
module.nomad_server.scaleway_server.server[1]: Creating...
module.nomad_server.scaleway_server.server[0]: Creating...

[...]

Apply complete! Resources: 9 added, 0 changed, 0 destroyed.
```



Could you please try to execute the terraform in debug mode and try to find potential clues? You can send the trace here ? **Do not forget to anonymize it** (cf. remove token, etc.).

```bash
$ TF_LOG=DEBUG terraform apply
```

**Comment by remyleone** [comment]
Hi, @silkysulky I'm going to close this issue. If your problem appears again, feel free to open a new issue :)
