### ISSUE TITLE
Recode data sources and add missing ones

### ISSUE THREAD

**Issue by QuentinBrosse** [terraform-providers/terraform-provider-scaleway#225]
Recode all data sources of this provider to:
-  Use the new [Scaleway Go SDK](https://github.com/scaleway/scaleway-sdk-go)
-  Improve the user experience

They will follow this scheme to support multi-product and to be consistent with the new [resource scheme](https://github.com/terraform-providers/terraform-provider-scaleway/issues/143):
```
scaleway_{product}_{resource}
```

### Storage

- ~`scaleway_storage_object_bucket` [#tba]~

### Compute

- `scaleway_image` → `scaleway_instance_image` [#359]
- `scaleway_instance_server` [#102]
- `scaleway_instance_ip` [#tba]
- `scaleway_security_group` → `scaleway_instance_security_group` [#346]
- `scaleway_volume` → `scaleway_instance_volume` [#356]
- `scaleway_bootscript` → `scaleway_instance_bootscript` [#tba]

### Marketplace

- `scaleway_image` → `scaleway_marketplace_image` [#276]

**Comment by abitrolly** [comment]
I would still drop `_instance_` from prefix. )

**Comment by QuentinBrosse** [comment]
@abitrolly: We will have resource name collisions: 
- `scaleway_compute_instance_server`
- `scaleway_compute_baremetal_server`

We also want to keep it simple for users by naming resources and data sources the same way.

**Comment by abitrolly** [comment]
@abitrolly why not to drop `_server` then? Because following your model above I will need to do too much micro housekeeping.

* `scaleway_compute_instance_ip` 
* `scaleway_compute_baremetal_ip`

There is no reason to not let API handle IP assignment transparently without these low level details providing just `scaleway_ip` on this level.

**Comment by QuentinBrosse** [comment]
@abitrolly I agree with you but today our API is as it is for the moment. Keep in mind that our APIs as our Terraform will evolve continuously. :)

**Comment by QuentinBrosse** [comment]
@abitrolly I agree with you but today our API is as it is for the moment. Keep in mind that our APIs as our Terraform will evolve continuously. :)

**Comment by abitrolly** [comment]
@QuentinBrosse I don't think that breaking API is good strategy for a DevOps tool. Unless there are solid tested migrations for every step, which increases overhead too much in the long run.

**Comment by QuentinBrosse** [comment]
@abitrolly I agree on this point but it will introduce to much overhead, flakiness and corner cases management to create a high level `scaleway_ip` resource. We don't want to do it for the moment.
If we do it one day, we will provide you a migration tool to update automatically your configuration files.

**Comment by abitrolly** [comment]
Fair enough. If you going to break API anyway, getting back to `scaleway_ip` should be no problem as long as API version is tracked somewhere.
