### ISSUE TITLE
When refreshing state of deleted scaleway_instance_ip, terraform plan stop on an HTTP 403

### ISSUE THREAD

**Issue by gileri** [terraform-providers/terraform-provider-scaleway#261]
# Terraform Version
Terraform v0.12.9
+ provider.scaleway v1.11.0

### Affected Resource(s)
- scaleway_ip

### Debug Output
https://gist.github.com/gileri/651f8a3cea93864cafbc75c47260413b

### Expected Behavior
The HTTP 403 error should be expected when scaleway_instance_ip are present in state, but not on Scaleway

### Actual Behavior
The 403 error stops `terraform plan`

### Steps to Reproduce
1. `terraform apply`
2. Remove instance IP from the web interface
3. `terraform plan`

**Comment by jerome-quere** [comment]
Hello @gileri,

Thank you for your report.
From the logs you send, it looks like you are using deprecated resource  `scaleway_ip` and not `scaleway_instance_ip`. 

The problem you are facing was fixed in the new `scaleway_instance_ip` (https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/scaleway/resource_instance_ip.go#L98)

Switching to the new resource should fix your problem.

**Comment by gileri** [comment]
Hello @jerome-quere, thank for your response !

I edited the OP as you're right, it was a `scaleway_ip` and not a `scaleway_instance_ip`.

In fact I got the error while migrating to new resources, and could not refresh state. Do you think a workaround will be implemented for users having not yet migrated (or are in the process to) to the new resources, or should I close the issue ?

**Comment by jerome-quere** [comment]
We write a migration guide available here: https://www.terraform.io/docs/providers/scaleway/guides/migration_guide_v2.html

Unfortunately, there is no easy way to migrate Terraform state between 2 resources.

One solution would be to import the state from an older resource. You can do that using the command
```
terraform import scaleway_instance_ip.myip fr-par-1/xxxx-xxxxx-ip-id
```
This command will hydrate the state of a resource from an existing IP.

This command should be done for each of your resources.

Hope this helps.

I let this issue open as we might try to fix the `scaleway_ip` issue in the next release even if it stay deprecated.
