### ISSUE TITLE
Cannot import a scaleway_instance_server that has been restored from a backup

### ISSUE THREAD

**Issue by gileri** [terraform-providers/terraform-provider-scaleway#270]
### Terraform Version
Terraform v0.12.9
+ provider.scaleway v1.11.0

### Affected Resource(s)
- scaleway_instance_server

### Debug Output
```scaleway-sdk-go: could not parse application/json response body: json: cannot unmarshal string into Go struct field Image.from_server of type instance.ServerSummary```

JSON response received from Scaleway API :
```
{"server": {"allowed_actions": ["poweroff", "terminate", "reboot", "stop_in_place", "backup"],[...],"from_server": "11111111-2222-3333-4444-555555555555", [...]}
```

### Expected Behavior
The `scaleway_instance_server` should have been imported successfully

### Actual Behavior
Resource not imported.

### Steps to Reproduce
1. Restore a server from a backup
2. Try to import it into a `scaleway_instance_server` resource

### Important Factoids
Import works correctly on a "fresh" server (not restored from backup), as the JSON property `"from_server": null`

### References
SDK Field : https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/instance_sdk.go#L2114

Expected object structure instead of string : https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/instance_sdk.go#L1034

**Comment by QuentinBrosse** [comment]
Hi @gileri 👋 !

Thanks for reporting this bug and sorry for the trouble.
We will fix it in the [v1.12.0](https://github.com/terraform-providers/terraform-provider-scaleway/milestone/4) who will be released before the end of the next week.

**Comment by asthomasdk** [comment]
I get the same error when trying to create new resources using an image that was created from a backup of another instance. 

Any ETA on the fix for this?

**Comment by QuentinBrosse** [comment]
Hi,
This issue has been fixed by fixing `scaleway-sdk-go` (https://github.com/scaleway/scaleway-sdk-go/issues/207) and by #281.

This fix will be released in the [v1.12.0](https://github.com/terraform-providers/terraform-provider-scaleway/milestone/4). It will be released next week.

Sorry for the inconvenience and thank you for reporting this issue 🤘!

**Comment by asthomasdk** [comment]
Any ETA on the v1.2.0 release? 

If possible, I'd like to use this to use terraform to fire up a big chunks of servers based on one of our images that we need for a workshop next week.

**Comment by QuentinBrosse** [comment]
Hi @asthomasdk,
We will release it this week.

**Comment by QuentinBrosse** [comment]
@asthomasdk,

For your information, the [v0.12.0](https://github.com/terraform-providers/terraform-provider-scaleway/releases/tag/v1.12.0) has been released last firday.

[Changelog](https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/CHANGELOG.md#1120-october-25-2019)

**Comment by gileri** [comment]
Thank you @QuentinBrosse !
