### ISSUE TITLE
instance_security_group: cannot create rules dynamically

### ISSUE THREAD

**Issue by dhenry-ceetiz** [terraform-providers/terraform-provider-scaleway#272]
### Terraform Version
Terraform v0.12.7 + provider.scaleway v1.11.0

### Affected Resource(s)
scaleway_instance_security_group

### Terraform Configuration Files
```hcl
provider "scaleway" {
  region  = "fr-par"
  zone    = "fr-par-1"
  version = "~> 1.11"
}

locals {
  trusted = ["192.168.0.1", "192.168.0.2"]
}

resource "scaleway_instance_security_group" "dummy" {
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    count = length(local.trusted)

    action = "accept"
    port   = 22
    ip     = local.trusted[count.index]
  }

}
```

### Debug Output
https://gist.github.com/dhenry-ceetiz/8310935d74591308ac54a8473993e54b

```
Error: Reference to "count" in non-counted context
```

### Expected Behavior
A new security group should be created with two inbound rules.

### Actual Behavior
The HCL is invalid because inbound_rule isn't a resource.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
This use to be feasible with (now deprecated) resources `scaleway_security_group` and `scaleway_security_group_rule`, because the latter also was a resource.

Bonus: it was also possible to implement Dependency Injection between terraform states:
1. State A: Declare a security group and add some servers to the security group.
1. State B: Create a server
1. State B: Inject state A (`terraform_remote_state`) and get the `scaleway_security_group`'s ID
1. State B: Add one `scaleway_security_group_rule` to the `scaleway_security_group` to white list the server from state B.

It's not possible anymore with `scaleway_instance_security_group` but maybe it was an antipattern.

**Comment by kindermoumoute** [comment]
Hi @dhenry-ceetiz you can use the new terraform pattern `for_each` to achieve this:
```hcl
provider "scaleway" {
  region  = "fr-par"
  zone    = "fr-par-1"
  version = "~> 1.11"
}

locals {
  trusted = ["192.168.0.1", "192.168.0.2"]
}

resource "scaleway_instance_security_group" "dummy" {
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"
  
  dynamic "inbound_rule" {
    for_each = local.trusted

    content {
      action = "accept"
      port   = 22
      ip     = inbound_rule.value
    }
  }
}
```


It works fine for me:
```
➜  terraform plan

...

Terraform will perform the following actions:

  # scaleway_instance_security_group.dummy will be created
  + resource "scaleway_instance_security_group" "dummy" {
      + id                      = (known after apply)
      + inbound_default_policy  = "drop"
      + name                    = (known after apply)
      + organization_id         = (known after apply)
      + outbound_default_policy = "accept"
      + zone                    = (known after apply)

      + inbound_rule {
          + action     = "accept"
          + ip         = "192.168.0.1"
          + port       = 22
          + port_range = (known after apply)
          + protocol   = "TCP"
        }
      + inbound_rule {
          + action     = "accept"
          + ip         = "192.168.0.2"
          + port       = 22
          + port_range = (known after apply)
          + protocol   = "TCP"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

...

➜  terraform version
Terraform v0.12.10
+ provider.scaleway v1.11.0
```

Let me know is this solve your issue.

**Comment by kindermoumoute** [comment]
I'm closing this since the `for_each` feature achieve the expected behavior.

**Comment by dhenry-ceetiz** [comment]
Thanks for the feedback (I thought `for_each` wasn't ready in terraform yet – my bad) and sorry for my slow answer.  
I'll open a separate ticket for the Dependency Injection question later.
