### ISSUE TITLE
SSH account key validation fails

### ISSUE THREAD

**Issue by ig0rsky** [terraform-providers/terraform-provider-scaleway#302]
Hi there,

### Terraform Version
Terraform v0.12.12
+ provider.scaleway v1.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- scaleway_account_ssh_key

### Terraform Configuration Files
```hcl
resource "scaleway_account_ssh_key" "ssh_key_main" {
  for_each = local.ssh_keys

  name = each.key
  public_key = file(each.value)
  
}
```
### Expected Behavior
SSH keys created

### Actual Behavior
scaleway-sdk-go: http error 400 Bad Request: Validation Error

### Steps to Reproduce
1. `terraform apply`

**Comment by kindermoumoute** [comment]
Hi @ig0rsky, I could reproduce your bug and it looks like it is triggered by `file(each.value)` which will add the newline character `\n` at the end of your ssh key.

You can use terraform's `chomp` function to fix it for now:
```hcl
resource "scaleway_account_ssh_key" "ssh_key_main" {
  for_each = local.ssh_keys

  name = each.key
  public_key = chomp(file(each.value))
}
```

I will keep this issue open to make this the normal behavior for this resource.
