### ISSUE TITLE
creating a server hangs up until 1h timeout if boot fails

### ISSUE THREAD

**Issue by smola** [terraform-providers/terraform-provider-scaleway#31]
### Terraform Version
`v0.10.0` (from provider tests)

### Affected Resource(s)
- scaleway_server

### Terraform Configuration Files
N/A: `make testacc`

### Expected Behavior
Tests pass.

### Actual Behavior
Tests creating a C1 server hang up if there is a boot problem.

### Steps to Reproduce
`make testacc`

### Important Factoids
I started experiencing this over the last weekend. Probably related to an incident with boot failures on C1 instances: https://status.online.net/index.php?do=details&task_id=1094

I'm having problems with boot again, with C1 instances stopping immediately after starting, `waitForServerState` never sees `running` state.

Maybe the provider should react and fail earlier if it sees `stopping` status after creating and powering on a server? Or maybe timeout should be lower than 1 hour?

**Comment by nicolai86** [comment]
I’ll get in touch with the support if they have a way to determine stuck instances, maybe we can add a “smart” detection to the provider.

At the end of the day Scaleway should ensure this doesn’t happen, but that’s a different discussion.

**Comment by smola** [comment]
@nicolai86 I'm giving a try at adding support for detecting this (checking if we see stopping/sopped when we want running). If you find a more appropriate way, please share ;-)

Occasional problems with this wouldn't be a problem. But I'm getting C1 servers allocated to a faulty node very often (as in multiple times everyday).

I found this is actually not related to the problem they had over the weekend: https://status.online.net/index.php?do=details&task_id=1094
This seems to be booting failures that happen if your server is allocated to a faulty node. When that happens, the server transitions quite quickly starting -> stopping -> stopped, in ~1 minute.
