### ISSUE TITLE
How to do "scaleway_instances" ?

### ISSUE THREAD

**Issue by asthomasdk** [terraform-providers/terraform-provider-scaleway#311]
Hi there,

Are there any plans to implement something like AWS' "aws_instances" - that you can use to get a list of the instances that are created in a group of instances? 

I am trying to translate an AWS example to spin up a Rancher 2.x HA cluster with 3 master nodes and 3 works nodes - and need to get a list of the public and private IPs from  the instances that are created - to update DNS as well as the internal setup of the rancher cluster. 

Or - is there another way I can do this? Maybe using outputs that get updated as the instances are started?

**Comment by loicbourgois** [comment]
Hi @asthomasdk,

Using `for_each`, you can loop through a group of ressources.

Also, by default, public IPs are dynamic. You might want to create `scaleway_instance_ip`, and assign them to your other resources.

Maybe you can  try someythings like this : 

```
provider "scaleway" {
  organization_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  zone = "fr-par-1"
}

# 1 : create names for your instance ressources
locals {
  names = toset(["a", "b", "c"])
}

# 2 : create server instances
resource "scaleway_instance_server" "servers" {
  for_each = local.names
  name = each.value
  type = "DEV1-S"
  image = "ubuntu-bionic"
}

# 3 : create static public IP for each server, and attach it
resource "scaleway_instance_ip" "public_ips" {
  for_each = local.names
  server_id = scaleway_instance_server.servers[each.key].id
}

```

Let us know if it helps.

**Comment by remyleone** [comment]
Hello, @asthomasdk we hope this answer was informative. Let us know if you have other questions :)

**Comment by asthomasdk** [comment]
Thanks for this! 
I have been away from this for a while - but will certainly try it out when I get back to it.
