### ISSUE TITLE
Feature request: handle reverse dns entry for scaleway IPs

### ISSUE THREAD

**Issue by sblaisot** [terraform-providers/terraform-provider-scaleway#34]
Hi there,

### Terraform Version
```
Terraform v0.11.1
+ provider.scaleway v1.0.0
```

### Affected Resource(s)
- scaleway_ip

### Terraform Configuration Files
```hcl
resource "scaleway_ip" "server_ip" {
  reverse        = "myserver.mydomain.tld"
}
```

### Debug Output
N/A

`Error: scaleway_ip.server_ip: : invalid or unknown key: reverse`

### Expected Behavior
ip is created and reverse dns entry is set

### Actual Behavior
Currently, it is not possible to define the reverse DNS entry associated with a scaleway IP nor to manage it using terraform scaleway provider.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

Despite not documented, the scaleway API allows a "reverse" parameter to the `/ips/[ip-uuid]` endpoint that let you manage the reverse dns entry. It expects a string and defaults to empty string (reverse entry not created).

**Comment by nicolai86** [comment]
Note: `reverse` can not be set when creating new IPs. Looking into ways to update IPs after they have been created.
