### ISSUE TITLE
Supported scaleway_instance_server.security_groups

### ISSUE THREAD

**Issue by reversTeam** [terraform-providers/terraform-provider-scaleway#353]
Hi there,

Can you add the `scaleway_instance_server.security_groups`.

```
resource "scaleway_instance_security_group" "frontend" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

    inbound_rule {
      action = "accept"
      port = "80"
    }
}

resource "scaleway_instance_security_group" "backend" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

    inbound_rule {
      action = "accept"
      port = "22"
    }
}

resource "scaleway_instance_server" "test" {
  type = "DEV1-S"
  image = "<IMAGE_ID>"
  name = "test" # todo : aad region cluster

  tags = []

  connection {
    type        = "ssh"
    user        = "root"
    private_key = "/path/to/ssh-key"
    host        = "${self.public_ip}"
  }

  security_groups = [
    scaleway_instance_security_group.frontend.id,
    scaleway_instance_security_group.backend.id
  ]
}
```

The output results
```
Error: Unsupported argument

  on modules/rabbit/main.tf line 37, in resource "scaleway_instance_server" "test":
  37:   security_groups = [

An argument named "security_groups" is not expected here.
```

I want to create a different layers of security groups, and when my service is connected to multiple service it's not easy to merge all rules.

Equivalent on aws :
https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups

Yours,

**Comment by loicbourgois** [comment]
Hi @reversTeam ,

`scaleway_instance_server` does not support multiple security groups.

See [Scaleway API documentation](https://developers.scaleway.com/en/products/instance/api/#security-group-03531b) and [Scaleway Terraform Documentation](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html#security_group_id).

If you want to merge multiple `security_groups` into one, you'll have to do it manually.

Trying to build `merged_sg` with references to other `security_groups` IDs won't work, as `merged_sg` will only be updated if the IDs change, not if the content of the source security_groups change.

You could use something like this : 

```hcl
# 1: Create array of rules for the different security groups
locals {
  # create an array with the frontend rules only
  frontend_inbound_rules = [
    {
      action = "accept"
      port = "80"
    }
  ]
  # create an array with the backend rules only
  backend_inbound_rules = [
    {
      action = "accept"
      port = "22"
    }, {
      action = "accept"
      port = "23"
    }
  ]
  # create an array with all the rules
  merged_inbound_rules = concat(local.frontend_inbound_rules, local.backend_inbound_rules)
}

# 2: for each array of rules, create a corresponding security group
resource "scaleway_instance_security_group" "frontend_sg" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

  dynamic "inbound_rule" {
    for_each = local.frontend_inbound_rules
    content {
      action = inbound_rule.value.action
      port = inbound_rule.value.port
    }
  }
}

resource "scaleway_instance_security_group" "backend_sg" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

  dynamic "inbound_rule" {
    for_each = local.backend_inbound_rules
    content {
      action = inbound_rule.value.action
      port = inbound_rule.value.port
    }
  }
}

resource "scaleway_instance_security_group" "merged_sg" {
  inbound_default_policy = "drop"
  outbound_default_policy = "accept"

  dynamic "inbound_rule" {
    for_each = local.merged_inbound_rules
    content {
      action = inbound_rule.value.action
      port = inbound_rule.value.port
    }
  }
}

# 3: Use the different security groups
resource "scaleway_instance_server" "test" {
  type = "DEV1-S"
  image = "ubuntu-bionic"
  security_group_id = scaleway_instance_security_group.merged_sg.id
}
```

**Comment by reversTeam** [comment]
With merged role, I have `factoriel(combined_role)` on my Scaleway Console, it's not what I want.
 - sg_1
 - sg_2
 - sg_3

// useless security_roles
 - sg_1 + sg_2
 - sg_2 + sg_3
 - sg_1 + sg_3
 - sg_1 + sg_2 + sg_3

Do you see the differences?

In the console i see, can configure 1 instance with multiple secrurityGroup, not merged group.
It's planed to integrate this feature on Scaleway Terraform?

**Comment by jerome-quere** [comment]
The scaleway API does not provide a way to create a “composed” security group.

Unfortunately due to how Terraform internal system work we cannot implement this feature in the plugin directly.

Example:

```hf
resource "scaleway_instance_security_group" “sg1” {
   rules ....
}
resource "scaleway_instance_security_group" “sg2” {
    rules ....
}
resource "scaleway_instance_server" "test" {
  security_groups = [
    scaleway_instance_security_group.sg1.id,
    scaleway_instance_security_group.sg2.id
  ]
}
```

In this case, the update server would only be called by Terraform core only when sg1.id or sg2.id changes ( only the id value not the rules inside the sg )

This will make TF unreliable as if a rule is added in one of the SG, this modification would not be taken into account by the server.

The example shown up top by @loicbourgois is a good way to solve this problem relying on Terraform variables as a single source of truth to create all needed resources.
