### ISSUE TITLE
Add a new security group rule results in a scary plan

### ISSUE THREAD

**Issue by QuentinBrosse** [terraform-providers/terraform-provider-scaleway#364]
So, interesting case:
```
Terraform v0.12.16
+ provider.scaleway v1.12.0
```

Initial resource:
```tf
resource "scaleway_instance_security_group" "bastion-ams1" {
  inbound_default_policy = "drop"

  name        = "bastion-ams1"
  description = "bastion-ams1"

  inbound_rule {
    action = "accept"
    port   = 655
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 655
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 500
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 4500
  }

  inbound_rule {
    action = "accept"
    port   = 59184
  }
}
```

It's all already applied and good, so after terraform plan:
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

Now, when I change my resource to:
```tf
resource "scaleway_instance_security_group" "bastion-ams1" {
  inbound_default_policy = "drop"

  name        = "bastion-ams1"
  description = "bastion-ams1"

  inbound_rule {
    action = "accept"
    port   = 333
  }

  inbound_rule {
    action = "accept"
    port   = 655
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 655
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 500
  }

  inbound_rule {
    action   = "accept"
    protocol = "UDP"
    port     = 4500
  }

  inbound_rule {
    action = "accept"
    port   = 59184
  }
}
```

Notice, I have only added one inbound_rule at the beginning with port 333, my terraform plan looks like this:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # scaleway_instance_security_group.bastion-ams1 will be updated in-place
  ~ resource "scaleway_instance_security_group" "bastion-ams1" {
        description             = "bastion-ams1"
        id                      = "nl-ams-1/***** REMOVED *****"
        inbound_default_policy  = "drop"
        name                    = "bastion-ams1"
        organization_id         = "***** REMOVED *****"
        outbound_default_policy = "accept"
        zone                    = "nl-ams-1"

      ~ inbound_rule {
            action   = "accept"
          ~ port     = 655 -> 333
            protocol = "TCP"
        }
      ~ inbound_rule {
            action   = "accept"
            port     = 655
          ~ protocol = "UDP" -> "TCP"
        }
      ~ inbound_rule {
            action   = "accept"
          ~ port     = 500 -> 655
            protocol = "UDP"
        }
      ~ inbound_rule {
            action   = "accept"
          ~ port     = 4500 -> 500
            protocol = "UDP"
        }
      ~ inbound_rule {
            action   = "accept"
          ~ port     = 59184 -> 4500
          ~ protocol = "TCP" -> "UDP"
        }
      + inbound_rule {
          + action   = "accept"
          + port     = 59184
          + protocol = "TCP"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I haven't put much effort to investigate this further but I'm a bit scared to touch my infra with it ;-D

_Originally posted by @krzysztofantczak in https://github.com/terraform-providers/terraform-provider-scaleway/issues/125#issuecomment-562862215_

**Comment by QuentinBrosse** [comment]
Hi @krzysztofantczak,
I have opened this issue to isolate your question, the roadmap comment thread was not the best place to answer.

The security rules order is important and results in this little scary Terraform plan. Moreover, it does exactly what you expect from him. I have reproduced your use-case on my side, I have exactly the same plan and the applied updates were good.

Here are two screenshots of my inbound rules (in the console):

Before:
<img width="1089" alt="Screenshot 2019-12-09 at 14 30 49" src="https://user-images.githubusercontent.com/10938538/70440225-fdde3600-1a91-11ea-8e06-34374773ac74.png">

After:
<img width="1087" alt="Screenshot 2019-12-09 at 14 32 26" src="https://user-images.githubusercontent.com/10938538/70440435-7b09ab00-1a92-11ea-961d-de5283c00a02.png">

Note that we (as a provider) cannot change the way differences are displayed in Terraform.

I close this issue, feel free to reopen if I have missed something. :)

**Comment by jerome-quere** [comment]
For the record I would also like to add that the order of rules in a security group may be important.
Adding a rule in the first position will move down all existing rules. If you just want to add a rule and order is not important, you could just add it at the end of the list, the plan will be much smaller.
