### ISSUE TITLE
additional_volume_ids broken for new instances of scaleway_instance_server 

### ISSUE THREAD

**Issue by mongrelion** [terraform-providers/terraform-provider-scaleway#379]
### Terraform Version
```
 $ terraform -v
Terraform v0.12.18
+ provider.scaleway v1.13.0
```
### Affected Resource(s)
- `scaleway_instance_server`

### Terraform Configuration Files
The [example](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html#with-additional-volumes-and-tags) on the documentation is not good enough. It doesn't work out of the box. Here the full snippet found on the official documentation:
```hcl
resource "scaleway_instance_volume" "data" {
  size_in_gb = 100
}

resource "scaleway_instance_server" "web" {
  type = "DEV1-L"
  image = "ubuntu-bionic"

  tags = [ "hello", "public" ]

  root_volume {
    delete_on_termination = false
  }

  additional_volume_ids = [ scaleway_instance_volume.data.id ]
}
```

And here's the modified config that almost works but that leads anyway to the bug that I'm reporting.
The changes are:
- the `type` of the `scaleway_instance_volume` needs to be specified
- the `image` on the `scaleway_instance_server` is also no good. `debian_buster` seems to do the trick
- the `root_volume` default size is also not good. I had to specify `80` gigs for it to work
```hcl
resource "scaleway_instance_volume" "data" {
  size_in_gb = 100
  type = "l_ssd"
}

resource "scaleway_instance_server" "web" {
  type = "DEV1-L"
  image = "debian_buster"

  tags = [ "hello", "public" ]

  root_volume {
    size_in_gb = 80
    delete_on_termination = false
  }

  additional_volume_ids = [ scaleway_instance_volume.data.id ]
}
```

### Expected Behavior
The instance should be created successfully as specified in the documentation.

### Actual Behavior
```
Error: scaleway-sdk-go: http error 400 Bad Request: The total size of local-volume(s) of instances DEV1-L must be equal to 80GB
```
I have gotten the same results while trying with different machine types but still getting the same results.
If I remove the `additional_volume_ids`, the error stops appearing and the instance gets fully created.

### Steps to Reproduce
1. `terraform apply`

**Comment by kindermoumoute** [comment]
The expected volume `type` for this example to work is `b_ssd`.

```hcl
resource "scaleway_instance_volume" "data" {
  size_in_gb = 100
  type = "b_ssd"
}

resource "scaleway_instance_server" "web" {
  type = "DEV1-L"
  image = "ubuntu-bionic"

  tags = [ "hello", "public" ]

  root_volume {
    delete_on_termination = false
  }

  additional_volume_ids = [ scaleway_instance_volume.data.id ]
}
```

Read more about the difference between block storage and local storage on [the official documentation](https://developers.scaleway.com/en/products/instance/api/#volumes-7e8a39).

In a nutshell, a server must handle a very strict amount of GB of local volumes (80G for `DEV1-L`). Whereas block storage allows to mount a flexible size.

Keeping this issue opened until the doc is fixed.

**Comment by mongrelion** [comment]
Thank you so much for your prompt help.
