### ISSUE TITLE
Can't run baremetal instance - missing boot_type option 

### ISSUE THREAD

**Issue by mateuszlewko** [terraform-providers/terraform-provider-scaleway#392]
Hi there,

there is no option to specify boot type for `scaleway_instance_server`, so I can't create `C2-S` (baremetal) instance. Is there any workaround? Is this going to be added?

### Terraform Version
```
Terraform v0.12.20
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- scaleway_instance_server

### Terraform Configuration Files
```hcl
resource "scaleway_instance_server" "web" {
  type  = "C2S"
  # the rest similar as here: https://www.terraform.io/docs/providers/scaleway/r/instance_server.html
}
```

### Expected Behavior
Server instance should be created with default bootscript. 

### Actual Behavior
Got following error:
`Error: scaleway-sdk-go: http error 400 Bad Request: Incompatible boot method 'local' for hardware 'C2S'`
### Steps to Reproduce
1. `terraform apply`

**Comment by jerome-quere** [comment]
Hi @mateuszlewko,

Thank you for your issue. This is indeed a problem in the terraform plugin.
We'll have a look and try to fix it before the next release.
