### ISSUE TITLE
port_range results a 400 Bad Request error

### ISSUE THREAD

**Issue by gaeldb** [terraform-providers/terraform-provider-scaleway#399]
Hi team,

`port_range` usage occurs a 400 Bad Request error of the scaleway-sdk with a unlogical error `Port range should be a valid cidr range`

### Terraform Version
```
Terraform v0.12.20
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- scaleway_instance_security_group

### Terraform Configuration Files
```hcl
# Our security groups
resource "scaleway_instance_security_group" "test" {
  name = "test"
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    action = "accept"
    port_range = "16000-26000"
    protocol = "UDP"
  }
}
```

### Expected Behavior
What should have happened?

### Actual Behavior
Got following error:
`Error: scaleway-sdk-go: http error 400 Bad Request: Invalid port range. Port range should be a valid cidr range
`
### Steps to Reproduce
1. `terraform apply`

### References
- #120 
- #358

**Comment by Sh4d1** [comment]
Hey @gaeldb , this in "desired" behaviour. As stated in the error message, the port range should be a cidr range like

**Comment by Sh4d1** [comment]
It's not optimal, but it's an API limitation

**Comment by gaeldb** [comment]
> the port range should be a cidr range like

What do you mean, can you please give example?
It works with `port_range  = "22-23"` but not with `port_range  = "16-26"`

**Comment by Sh4d1** [comment]
It's not well documented but the difference between the two ports should be a power of 2 minus 1 iirc

**Comment by gaeldb** [comment]
Hurf, what?
Never heard about this port notation, which seems quite confusing... and restrictive.
Cannot have a choice on the range to open, that can implies real security issues :(

**Comment by Sh4d1** [comment]
I think it's Scaleway specific though :sweat_smile: But yep it's annoying :( It may work by combining ranges though but not really user friendly

**Comment by gaeldb** [comment]
Is there a small doc somewhere?
Cannot open a range larger than 15 ports
"10000-10015" OK (4²-1)
"10000-10024" KO (5²-1)

**Comment by Sh4d1** [comment]
@gaeldb power of 2 as in `2^5` and not `5^2` 😄

**Comment by gaeldb** [comment]
Obviously... my bad
Notation confused me
