### ISSUE TITLE
disable_dynamic_ip and enable_dynamic_ip attributes both exist on scaleway_instance_server

### ISSUE THREAD

**Issue by mdawar** [terraform-providers/terraform-provider-scaleway#415]
The attributes `disable_dynamic_ip` and `enable_dynamic_ip` both exist on the `scaleway_instance_server` resource at the same time, even though `disable_dynamic_ip` was removed in favor of `enable_dynamic_ip`:

```console
$ terraform validate

Error: "disable_dynamic_ip": [REMOVED] Removed in favor of enable_dynamic_ip

  on main.tf line 25, in resource "scaleway_instance_server" "web":
  25: resource "scaleway_instance_server" "web" {
```

I don't know if this is intentional or required somehow for the transition to `v2` but I thought that I should report it.

Also in the documentation `disable_dynamic_ip` is still being used in the [With a reserved IP](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html#with-a-reserved-ip) section:

```hcl
resource "scaleway_instance_ip" "ip" {}

resource "scaleway_instance_server" "web" {
  type = "DEV1-L"
  image = "f974feac-abae-4365-b988-8ec7d1cec10d"

  tags = [ "hello", "public" ]

  ip_id = scaleway_instance_ip.ip.id
  disable_dynamic_ip = true # required for now when using `ip_id`
}
```

### Terraform Version
```
Terraform v0.12.21
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- `scaleway_instance_server`

### Example `terraform apply` output

```console
  # scaleway_instance_server.testing must be replaced
-/+ resource "scaleway_instance_server" "testing" {
      - additional_volume_ids            = [] -> null
        disable_dynamic_ip               = false
        disable_public_ip                = false
        enable_dynamic_ip                = false
        enable_ipv6                      = true
        [...]
    }
```

**Comment by QuentinBrosse** [comment]
Thanks, it was already fixed in #413.
