### ISSUE TITLE
Possible issue with IPv6 enabled servers which are turned off

### ISSUE THREAD

**Issue by komarEX** [terraform-providers/terraform-provider-scaleway#42]
Hi there,

### Terraform Version
```
Terraform v0.11.3
+ provider.scaleway v1.0.1
```

### Affected Resource(s)
```
scaleway_server
```

### Terraform Configuration Files
```hcl
data "scaleway_image" "centos_7_3" {
  architecture = "x86_64"
  name         = "CentOS 7.3"
}

resource "scaleway_server" "test" {
  name        = "test"
  image       = "${data.scaleway_image.centos_7_3.id}"
  type        = "VC1M"
  tags        = ["test"]
  enable_ipv6 = true
  state       = "running"

  volume {
    size_in_gb = 50
    type       = "l_ssd"
  }
}
```

### Debug Output
N/A

### Panic Output
https://gist.github.com/komarEX/d993b7be3e96205d6a085bc56d1b21ca

### Expected Behavior
Should just work.

### Actual Behavior
Crashing terraform.

### Steps to Reproduce
1. Provision server with IPv6 enabled using terraform.
2. Turn off server manually (not by terraform).
3. Run `terraform plan`
4. Should crash on trying to reach IPv6 data in received json (key not exist? idk)

### Important Factoids
N/A

### References
N/A

**Comment by nicolai86** [comment]
@komarEX we just releases v1.1.0 which contains a fix for your crash. Please update to avoid the issue in the future :)

**Comment by komarEX** [comment]
I confirm it works now :) Thanks.
