### ISSUE TITLE
scaleway_account_ssh_key API timeout

### ISSUE THREAD

**Issue by mdawar** [terraform-providers/terraform-provider-scaleway#425]
Hi there,

The `scaleway_account_ssh_key` resource cannot be created because of an API timeout error, I've been getting this error for 2 days now after a 403 forbidden error related to [this issue](https://github.com/scaleway/scaleway-sdk-go/issues/282) on the Scaleway Go SDK repository.

```console
Error: scaleway-sdk-go: error executing request: POST https://api.scaleway.com/account/v2alpha1/ssh-keys giving up after 4 attempts
```

### Terraform Version
```console
Terraform v0.12.23
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- `scaleway_account_ssh_key`

### Terraform Configuration Files
```hcl
provider "scaleway" {
  version         = "1.13"
  organization_id = "<ORG_ID>"
  access_key      = "<ACCESS_KEY>"
  secret_key      = "<SECRET_KEY>"
  zone            = "fr-par-1"
  region          = "fr-par"
}

resource "scaleway_account_ssh_key" "test_key" {
  name       = "test_key"
  public_key = "<PUBLIC_SSH_KEY>"
}
```

### Expected Behavior
A `scaleway_account_ssh_key` resource should be created.

### Actual Behavior
The `scaleway_account_ssh_key` is not being created because of an API timeout.

### Steps to Reproduce
1. `terraform apply`
```console
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # scaleway_account_ssh_key.test_key will be created
  + resource "scaleway_account_ssh_key" "test_key" {
      + id              = (known after apply)
      + name            = "test_key"
      + organization_id = (known after apply)
      + public_key      = "<PUBLIC_KEY>"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

scaleway_account_ssh_key.test_key: Creating...
scaleway_account_ssh_key.test_key: Still creating... [10s elapsed]

Error: scaleway-sdk-go: error executing request: POST https://api.scaleway.com/account/v2alpha1/ssh-keys giving up after 4 attempts

  on main.tf line 10, in resource "scaleway_account_ssh_key" "test_key":
  10: resource "scaleway_account_ssh_key" "test_key" {

```

**Comment by mbugeia** [comment]
I've noticed the same issue. It seems to have something to do with the key length, a short key (ssh-ed25519 for example) can be created correctly but not a 4096bits RSA key.

**Comment by mdawar** [comment]
@mbugeia Yes you're right I'm using a 4096 bits RSA key, I have just tried it with a 2048 bits key and it's working.

**Comment by jerome-quere** [comment]
Hi @mbugeia,

This error:
```
Error: scaleway-sdk-go: error executing request: POST https://api.scaleway.com/account/v2alpha1/ssh-keys giving up after 4 attempts
```
is linked effectively linked to https://github.com/scaleway/scaleway-sdk-go/issues/282

It should be resolved soon on the API side. I will update both issue when fix is deployed.

**Comment by jerome-quere** [comment]
Hi @mdawar, The problem should be fixed. Can you git it a try?

**Comment by mdawar** [comment]
Hi @jerome-quere, I have tested it and yes this issue was resolved, but why the created SSH keys do not show up on the credentials page in the web console?

Thank you.

**Comment by QuentinBrosse** [comment]
Hi @mdawar,
You have to logout / login to see them in the console. Maybe we should improve it.
