### ISSUE TITLE
ip_range does not support ipv6

### ISSUE THREAD

**Issue by nikaro** [terraform-providers/terraform-provider-scaleway#481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.scaleway v1.13.0

### Affected Resource(s)

* scaleway_scaleway_instance_security_group
* scaleway_instance_security_group_rules

### Terraform Configuration Files

```hcl
inbound_rule {
  action = "accept"
  port = 22
  ip_range = "2a01:e7a:2fc:24f6::/64"
}
```

### Debug Output

https://gist.github.com/nikaro/f043fcf1a466f017595e8f4d05a82b45

### Panic Output

https://gist.github.com/nikaro/2b8b45f4249c331875a64ba5263a5452

### Expected Behavior

`ip_range` should allow to set IPv6 range.

### Actual Behavior

```
Error: expected "inbound_rule.7.ip_range" to contain a network CIDR with between 0 and 32 significant bits, got: 64

  on infra_security_groups.tf line 3, in resource "scaleway_instance_security_group" "bastion":
   3: resource "scaleway_instance_security_group" "bastion" {
```

### Steps to Reproduce

1. `terraform plan`

**Comment by nikaro** [comment]
Here is the code responisble of the failure:

```go
"ip_range": {
	Type:         schema.TypeString,
	Optional:     true,
	ValidateFunc: validation.CIDRNetwork(0, 32),
	Description:  "Ip range for this rule (e.g: 192.168.1.0/24). Only one of ip or ip_range should be provided",
},
```

https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/scaleway/resource_instance_security_group.go#L420 and certainly somewhere else.

I don't know where does the `validation.CIDRNetwork` function come from, but it should detect wether it is an IPv4 or IPv6 subnet and then check against the appropriated netmask (32 vs 128).

**Comment by Sh4d1** [comment]
@nikaro fix incoming :smile:

**Comment by nikaro** [comment]
Great, i'm curious to see how you intend to fix this.

I started looking and thought that may be it should be fixed in the [`validation.CIDTNetwork`](https://github.com/terraform-providers/terraform-provider-scaleway/blob/f2de2831598181836f87322e4c34802d48bddaaf/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/validation.go#L206) function instead. May be its arguments should be optional, since it already uses [`net.ParseCIDR`](https://golang.org/pkg/net/#ParseCIDR) that probably does a great job at checking valid CIDR.

**Comment by Sh4d1** [comment]
Huh good catch, just need to increase the max allowed since it's already doing ipv4/v6 check :wink:
