### ISSUE TITLE
autoscaled size of kubernetes node pool gets shrunk

### ISSUE THREAD

**Issue by boredland** [terraform-providers/terraform-provider-scaleway#484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`Terraform v0.12.24`

### Affected Resource(s)
* scaleway_k8s_pool_beta

### Terraform Configuration Files

```hcl
resource "scaleway_k8s_pool_beta" "pool0" {
  cluster_id          = scaleway_k8s_cluster_beta.clustername.id
  name                = "pool0"
  node_type           = "DEV1-M"
  size                = 3
  autoscaling         = true
  autohealing         = true
  wait_for_pool_ready = true
  min_size            = 3
  max_size            = 6
}
```

### Expected Behavior

I expect actual sizes of the pool between 3 and 6 to take precendence the `size` of 3.

### Actual Behavior

Given the cluster has a size bigger then 3, it gets shrunk to the size of 3 during plan&apply.

**Comment by Sh4d1** [comment]
Hey @boredland ! What version of the TF provider are you using?

**Comment by boredland** [comment]
```
Terraform v0.12.24
+ provider.aws v2.61.0
+ provider.cloudflare v2.6.0
+ provider.digitalocean v1.18.0
+ provider.external v1.2.0
+ provider.github v2.7.0
+ provider.google v3.20.0
+ provider.google-beta v3.20.0
+ provider.kubernetes v1.11.2
+ provider.local v1.4.0
+ provider.mongodbatlas v0.5.1
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.scaleway v1.15.0
```

**Comment by Hades32** [comment]
I think I have a similar problem. I created a pool with size=1, min=1 and max=5. The autoscaling changed the size to 2. As soon as I run my terraform apply, the provider detects this as a change and tries to scale down again. (not sure of it really does).

IMHO the field should be renamed from `size` to `initial_size` and should only affect initial pool creation.

**Comment by Sh4d1** [comment]
@Hades32 with the 1.15 of the provider ?

**Comment by Hades32** [comment]
yes, actually a build from master

**Comment by Sh4d1** [comment]
Yes indeed :sweat_smile: (though the pool is not updated). @Hades32 #498 should fix it :)
