### ISSUE TITLE
invalid_request_error The total volume size of VC1M instances must be equal to 100GB

### ISSUE THREAD

**Issue by bithavoc** [terraform-providers/terraform-provider-scaleway#50]
Hi,

### Terraform Version
```
Terraform v0.11.4
+ provider.scaleway v1.2.
```

### Affected Resource(s)
Please list the resources as a list, for example:
- scaleway_server

### Terraform Configuration Files
```hcl
data "scaleway_image" "ubuntu" {
  architecture = "x86_64"
  name         = "Ubuntu Xenial"
}
resource "scaleway_server" "rancher_master" {
  name  = "rancher_master"
  image = "${data.scaleway_image.ubuntu.id}"
  type  = "VC1S"
}
```

### Expected Behavior
Server gets created successfully

### Actual Behavior
I keep seeing:

```
Error: Error applying plan:

1 error(s) occurred:

* scaleway_server.rancher_master: 1 error(s) occurred:

* scaleway_server.rancher_master: StatusCode: 400, Type: invalid_request_error, APIMessage: The total volume size of VC1M instances must be equal to 100GB
```

Adding `volume` as suggested in https://github.com/hashicorp/terraform/issues/9254 doesn't help either:
```
  volume {
    size_in_gb = 100
    type = "l_ssd"
  }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
- https://github.com/hashicorp/terraform/issues/9254

**Comment by AlbanMontaigu** [comment]
Since the server is delivered with a system volume of 50Gb you need to specify an additional volume of 50Gb

`volume {
    size_in_gb = 50
    type = "l_ssd"
  }`

Then the total will be 100

**Comment by nicolai86** [comment]
@bithavoc the solution to this was implemented in https://github.com/hashicorp/terraform/pull/9695.

This works for any instance requiring 100GB or more base storage:

```
resource "scaleway_server" "test" {
  name = "test"
  image = "5faef9cd-ea9b-4a63-9171-9e26bec03dbc"
  type = "VC1M"

  volume {
    size_in_gb = 50
    type = "l_ssd"
  }
}
```

**Comment by ars0** [comment]
I think I have the same problem with other instance type: 
`Terraform v0.11.7
+ provider.scaleway v1.4.1`

`data "scaleway_image" "ubuntu" {
  architecture = "x86_64"
  name         = "Ubuntu Xenial"
}

resource "scaleway_server" "test-srv-tf" {
  name  = "test-name-sw"
  image = "${data.scaleway_image.ubuntu.id}"
  type  = "START1-XS"
  dynamic_ip_required = true
}`

Adding such things do not fix the problem
`  volume {
    size_in_gb = 10
    type = "l_ssd"
  }
`

I'm getting 
`* scaleway_server.test-srv-tf: StatusCode: 400, Type: invalid_request_error, APIMessage: The total volume size of START1-XS instances must be equal to 25GB`

**Comment by bithavoc** [comment]
I couldn't make it work, gave up trying to use Terraform with Scaleway

**Comment by barikamada** [comment]
This code creates VM of START1-XS type:
```
data "scaleway_image" "ubuntu-xenial" {
  architecture  = "x86_64"
  name          = "Ubuntu Xenial"
}

resource "scaleway_server" "test" {
  name  = "test"
  image = "${data.scaleway_image.ubuntu-xenial.id}"
  type  = "START1-XS"

  volume {
    size_in_gb = 5
    type       = "l_ssd"
  }
}
```

**Comment by barikamada** [comment]
You have to use Ubuntu_Mini_Xenial_25G image when you create START1-XS server:
```
data "scaleway_image" "ubuntu-mini" {
  architecture = "x86_64"
  name         = "Ubuntu Mini Xenial 25G"
}
resource "scaleway_server" "test-xs" {
  name  = "test-xs"
  image = "${data.scaleway_image.ubuntu-mini.id}"
  type  = "START1-XS"
}
```
