### ISSUE TITLE
Create bugfix releases regularly

### ISSUE THREAD

**Issue by Hades32** [terraform-providers/terraform-provider-scaleway#509]
It has been a few weeks until some (for me critical) bugs have been fixed, but there still is no 1.15.1 release containing the fix. So I need to build it myself and hack Terraform to use my local build. That's a pretty bad situation.

Assuming that your master branch is always good, why don't you create patch releases asap or at least once a week?

**Comment by jerome-quere** [comment]
Hi @Hades32 ,

I'm really sorry we couldn't keep a correct Terraform release cycle for the past month.
This does not reflect our quality goals for this provider and other Scaleway open-source software.
I'll make sure we package a release next week.

Thank you for your feedback and for using the Scaleway Provider.

**Comment by Hades32** [comment]
Thank you, that sounds great. Looking forward to it 👍

**Comment by gene1wood** [comment]
@Hades32 Out of curiosity, what bugs are you encountering that have been fixed but the fix hasn't been released? I'm trying to troubleshoot (what I think is) a bug in the scaleway terraform provider but I'd hate to find out that it was a bug that had been reported and fixed, just not released.

**Comment by Hades32** [comment]
For me it was usage of K8S resources with a different region than the
provider default region.

But you can just check the commits since 1.15. It's not too many

Gene Wood <notifications@github.com> schrieb am Sa., 27. Juni 2020, 23:20:

**Comment by jerome-quere** [comment]
🎉 v1.16.0 is out https://github.com/terraform-providers/terraform-provider-scaleway/blob/v1.16.0/CHANGELOG.md#1160-june-29-2020 sorry for the delay
