### ISSUE TITLE
Format missmatch between instance_ip.id and instance_server.ip_id

### ISSUE THREAD

**Issue by kaminek** [terraform-providers/terraform-provider-scaleway#522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
+ provider.scaleway v1.16.0

### Affected Resource(s)

* scaleway_instance_server
* scaleway_instance_ip

### Terraform Configuration Files

```hcl
resource "scaleway_instance_ip" "server_ip_0" {}
resource "scaleway_instance_ip" "server_ip_1" {}
resource "scaleway_instance_ip" "server_ip_2" {}

resource "scaleway_instance_server" "server" {
  count                 = var.server_count
  name                  = "${var.name}-server-${count.index}"
  type                  = var.server_instance_type
  image                 = "ubuntu-bionic"
  tags                  = ["server"]
  ip_id                 = "scaleway_instance_ip.server_ip_${count.index}.id"
  security_group_id     = scaleway_instance_security_group.generic.id
  root_volume {
    delete_on_termination = "true"
  }

```

### Error Output

```
Error: scaleway-sdk-go: invalid argument(s): ip_address does not respect constraint, scaleway_instance_ip.server_ip_1.id is not a valid UUID.

  on modules/nomad/nomad.tf line 41, in resource "scaleway_instance_server" "server":
  41: resource "scaleway_instance_server" "server" {

```
### Expected Behavior

Well attach Public IP to Instance

### Actual Behavior

Fail with Error

### Steps to Reproduce

1. `terraform apply`
2. See the Error

### Important Factoids
```hcl
# module.nomad.scaleway_instance_ip.server_ip_0:
resource "scaleway_instance_ip" "server_ip_0" {
    address         = "51.158.104.145"
    id              = "fr-par-1/508296d1-6813-45df-963b-cc970f4a8e39"
    organization_id = "<hidden>"
    zone            = "fr-par-1"
}

# module.nomad.scaleway_instance_server.server[0]:
resource "scaleway_instance_server" "server" {
    additional_volume_ids = []
    boot_type             = "local"
    disable_dynamic_ip    = false
    disable_public_ip     = false
    enable_dynamic_ip     = false
    enable_ipv6           = false
    id                    = "fr-par-1/fc5324f5-94d4-429a-91b2-89e706b8e0e0"
    image                 = "ubuntu-bionic"
    ip_id                 = "scaleway_instance_ip.server_ip_0.id"
    ipv6_prefix_length    = 0
    name                  = "nomad-server-0"
    private_ip            = "10.68.28.35"
    security_group_id     = "fr-par-1/fe4c105c-e5d2-48d8-8e29-9ceeb9ba9976"
    state                 = "started"
    tags                  = [
        "nomad",
        "server",
    ]
    type                  = "DEV1-S"
    zone                  = "fr-par-1"

    root_volume {
        delete_on_termination = true
        size_in_gb            = 20
        volume_id             = "fr-par-1/7b855926-5777-445b-beaa-85288fff1400"
    }
}
```
The resource `scaleway_instance_server.ip_id` accepts a UUID but it seems that `scaleway_instance_ip.id` is in the wrong format `<zone>/<uuid>`
And the [documentation](https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/website/docs/r/instance_ip.html.markdown) is not up to date

### References

* https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/website/docs/r/instance_ip.html.markdown
* https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/website/docs/r/instance_server.html.markdown#arguments-reference

**Comment by jerome-quere** [comment]
Hello @kaminek 
It looks like the problem in your tf file
```
ip_id = scaleway_instance_ip.server_ip_0.id <= Take the id attribute of scaleway_instance_ip.server_ip_0 resource

VS

ip_id = "scaleway_instance_ip.server_ip_${count.index}.id" <=  Try to use "scaleway_instance_ip.server_ip_0.id" string as the UUID.

```

If I understand correctly you are trying to do something like

```
provider "scaleway" {
}

locals {
  replicas = 3
}

resource scaleway_instance_ip "ip" {
  count = local.replicas
}

resource scaleway_instance_server "server" {
  count = local.replicas
  ip_id = scaleway_instance_ip.ip[count.index].id
  image = "ubuntu_focal"
  type = "DEV1-S"
}

```

**Comment by kaminek** [comment]
Hi @jerome-quere ,

You are right it's a mistake of mine in the tf declaration, closing
Thx
