### ISSUE TITLE
Provider has stopped working

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-scaleway#60]
### Terraform Version
```
Terraform v0.11.7
+ provider.scaleway v1.3.0
```

### Affected Resource(s)
data.scaleway_image

### Terraform Configuration Files
```hcl
data "scaleway_image" "ubuntu" {
  architecture = "x86_64"
  name         = "Ubuntu Zesty"
}

data "scaleway_image" "openvpn" {
  architecture = "x86_64"
  name         = "OpenVPN"
}
```

### Debug Output
```
data.scaleway_image.ubuntu: Refreshing state...
data.scaleway_image.openvpn: Refreshing state...
2018/04/27 15:23:44 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.scaleway_image.openvpn: The query returned no result. Please refine your query.
2018/04/27 15:23:44 [ERROR] root: eval: *terraform.EvalSequence, err: data.scaleway_image.openvpn: The query returned no result. Please refine your query.
2018/04/27 15:23:44 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.scaleway_image.ubuntu: The query returned no result. Please refine your query.
2018/04/27 15:23:44 [ERROR] root: eval: *terraform.EvalSequence, err: data.scaleway_image.ubuntu: The query returned no result. Please refine your query.
2018/04/27 15:23:44 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error refreshing state: 2 error(s) occurred:

* data.scaleway_image.openvpn: 1 error(s) occurred:

* data.scaleway_image.openvpn: data.scaleway_image.openvpn: The query returned no result. Please refine your query.
* data.scaleway_image.ubuntu: 1 error(s) occurred:

2018-04-27T15:23:44.166-0400 [DEBUG] plugin: plugin process exited: path=/home/ansible/repos/scaleway-kubernetes-infra/.terraform/plugins/linux_amd64/terraform-provider-scaleway_v1.3.0_x4
* data.scaleway_image.ubuntu: data.scaleway_image.ubuntu: The query returned no result. Please refine your query.
```
### Expected Behavior
My 'terraform plan' operation should have completed.

### Actual Behavior
Error
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
This has worked for months and last worked a week or so ago. Now it doesn't work. My token is still valid. I was able to hit the API via curl. Possible they somehow broke the api for the terraform client?

**Comment by nicolai86** [comment]
@shadycuz I’m sorry for the inconvenience. As you can see from the terraform plan output, the query for the image returns no data any more.

Did you validate that Ubuntu Zesty is still accessible as a image? Ubuntu Zesty is not a LTS release so I’d expect Scaleway to remove the image once it reaches EOL. EOL was January 13th.

**Comment by shadycuz** [comment]
@nicolai86 

Yes both images are still listed 
![image](https://user-images.githubusercontent.com/17090999/39381952-dffdfb2a-4a31-11e8-8325-459326c17e55.png)

Let me test by listing the images via the API with curl.

**Comment by shadycuz** [comment]
I would have to curl through all the pages.

**Comment by nicolai86** [comment]
I’ll take a look. Thanks for the report!

**Comment by nicolai86** [comment]
@shadycuz I've confirmed via the API that there is no x86_64 image for OpenVPN at the moment:

x86_64
```
# curl 'https://api-marketplace.scaleway.com/images?arch=x86_64'  | jq -r '.images[].name'
Debian Jessie
Ubuntu Xenial
Python
Docker
Golang
Gogs
Node.js
ownCloud
Java
Ruby
Fedora 27
CentOS 7.4
Arch Linux
Debian Stretch
Alpine Linux
Ubuntu Mini Xenial 25G
```

ARM
```
# curl 'https://api-marketplace.scaleway.com/images?arch=arm'  | jq -r '.images[].name'
Redis
Camlistore
Serendipity
ZeroBin
Ruby on Rails
Etherpad
Discourse
Fedora
openSUSE
Kanboard
Syncthing
Jenkins Master
Pydio
Jenkins Slave
Drupal
Minecraft
Ghost
ELK stack
PrestaShop
Gentoo
Redmine
CentOS 7.2
LEMP stack
Image Builder
Webmin
Ubuntu Precise
Ubuntu Wily
Ubuntu Yakkety
Ubuntu Trusty
GitLab
Debian Sid
Ubuntu Zesty
WordPress
OpenVPN
Torrents
Debian Jessie
Ubuntu Xenial
Python
Docker
Golang
Gogs
Node.js
ownCloud
Java
Debian Wheezy
Ruby
Debian Stretch
```

**Comment by nicolai86** [comment]
Please check with Scaleway support what happened to the missing image.

**Comment by nicolai86** [comment]
Thank you for reaching out to Scaleway. I’ll leave the issue open for some time; maybe they’ll fix the missing image quickly.

**Comment by hadret** [comment]
hm, I'm not 100% it's related, but does look very similar to the issue I'm hitting. I'm fetching UUIDs of the images via `scw images -f name=ubuntu -q`. unfortunately, none appear to be working. I tried Xenial and Bionic and both are responding like so:

```* scaleway_server.test: StatusCode: 404, Type: unknown_resource, APIMessage: "3dcbd786-27f9-41c8-887e-cb468a877517" not found```

way to reproduce:

1. fetch the image UUID:

```
scw images -f name=ubuntu -q
```

2. prepare simple terraform plan:

```
provider "scaleway" {
  region       = "par1"
}

resource "scaleway_server" "test" {
  name       = "test"
  image      = "3dcbd786-27f9-41c8-887e-cb468a877517"
  type       = "C2S"
  tags       = ["test"]
}
```

3. fail:

```
* scaleway_server.test: StatusCode: 404, Type: unknown_resource, APIMessage: "3dcbd786-27f9-41c8-887e-cb468a877517" not found
```

**Comment by nicolai86** [comment]
@hadret do you have a reason for not using the data source to lookup images? Otherwise you need to make sure datacenter & architecture match.

**Comment by hadret** [comment]
no, I don't. fair point, I will try it out tomorrow and get back here -- on the other hand, these two particular images are super generic and they support all of the architectures for both datacenters.

**Comment by hadret** [comment]
ok, using data source fixed the issue for me. strange, that the uuid is different though...

**Comment by sieben** [comment]
@shadycuz OpenVPN images exist for x86_64. Could you check again if you can instantiate one?

**Comment by shadycuz** [comment]
@sieben They have added the missing images. This had to do with this https://blog.online.net/2018/04/19/scaleway-feature-improvements-custom-kernel-security-group-live-reload-imagehub-packer/. 

Thanks all.
