### ISSUE TITLE
Could not instanciate a START1-M server

### ISSUE THREAD

**Issue by cnouguier** [terraform-providers/terraform-provider-scaleway#64]
Hi,

I'm facing an issue when trying to create an instance of type of START-1M. The instance has a volume of 100GO and Terraform raise an error.  
Am I doing something wrong ?

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.20.0
+ provider.null v1.0.0
+ provider.scaleway v1.4.1
```

### Affected Resource(s)
scaleway_server

### Terraform Configuration Files
https://github.com/kalisio/kaabah/blob/swarm/modules/Scaleway/scw-workers.tf
https://github.com/kalisio/kaabah/blob/swarm/modules/Scaleway/scw-manager.tf

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* module.Scaleway.scaleway_server.swarm_manager: 1 error(s) occurred:

* scaleway_server.swarm_manager: StatusCode: 400, Type: invalid_request_error, APIMessage: The total volume size of START1-M instances must be equal to 100GB
```
### Panic Output

See above

### Expected Behavior

Expecting to have a START1-M instance

### Actual Behavior

Error

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/kalisio/kaabah/tree/swarm

**Comment by nicolai86** [comment]
@cnouguier I think this is similar to https://github.com/terraform-providers/terraform-provider-scaleway/issues/50. 

Adding an inline volume like this should fix your issue

```
resource "scaleway_server" "test" {
  name = "test"
  image = "5faef9cd-ea9b-4a63-9171-9e26bec03dbc"
  type = "START-1M"

  volume {
    size_in_gb = 50
    type = "l_ssd"
  }
}
```

let me know if this works for you.

**Comment by cnouguier** [comment]
Hi @nicolai86 !
Indeed it works better. It might be worthwhile to clarify the documentation https://www.terraform.io/docs/providers/scaleway/r/server.html#volume-1 
Anyway, many thanks for your feedback.

**Comment by nicolai86** [comment]
@cnouguier thank you. I’ll keep this ticket open until the documentation has been clarified.

**Comment by nicolai86** [comment]
clarified the documentation in https://github.com/terraform-providers/terraform-provider-scaleway/commit/ebaf2f253896b515f9b05e00ef4b51a870490bd3

**Comment by nicolai86** [comment]
@tusharkhanka I think the default volume size is 50 gb so you need to add another 50gb, not 100.

does that work for you?

**Comment by cnouguier** [comment]
@tusharkhanka  You may have a look at the code here: https://github.com/kalisio/kaabah/blob/master/modules/Scaleway/scw-manager.tf#L13
It adds the volume on the server according to its type. The mapping server type/volume size is defined here: https://github.com/kalisio/kaabah/blob/master/modules/Scaleway/scw-variables.tf#L85

Hope it helps.

**Comment by nrxr** [comment]
This should be documented somewhere. The comment at https://github.com/terraform-providers/terraform-provider-scaleway/issues/64#issuecomment-393410937 worked as a hint for me.

Was trying to create `X64-15GB` instances and without the volume thing gave me:
```
* scaleway_server.instance: StatusCode: 400, Type: invalid_request_error, APIMessage: Volume size 200000000000 is bigger than maximum size 150000000000 required for volume-type l_ss
d
```

Then, tried attaching volumes and gave me the same problem. After trying the volume inline things started to work, the solution is using the volume inline for the extra after the 50GB. So in the case of X65-15GB, the total for the starting point is 200GB, so you need to add an inline of 150GB, like:

```
  volume {
    size_in_gb = 150
    type = "l_ssd"
  }
```

Hope that adding the error helps more people.

**Comment by nrxr** [comment]
The only pending issue is that when you run a `terraform destroy` it will only remove the inline volume, not the base one.
