### ISSUE TITLE
Server creation appears to happen sequentially

### ISSUE THREAD

**Issue by lyptt** [terraform-providers/terraform-provider-scaleway#65]
### Terraform Version
Terraform v0.11.7
+ provider.scaleway v1.4.1

### Affected Resource(s)
- scaleway_server

### Terraform Configuration Files
[tf.zip](https://github.com/terraform-providers/terraform-provider-scaleway/files/2062095/tf.zip)

### Expected Behavior
Servers are created in parallel

### Actual Behavior
Servers are created synchronously, making `tf apply` mega slow

### Steps to Reproduce
1. `terraform apply`

**Comment by nicolai86** [comment]
@lyptt thank you for this suggestion! We had some issues in the past with scaleways API returning errors for parallel created resources.

I reaches out to the support some time ago and they told me that parallel requests aren’t safe atm within the same session.

This is why the terraform provider chose to be slow, but at least more reliable.

I’ll pick up the discussion with Scaleway again. Maybe @sieben can chime in with some details.

**Comment by lyptt** [comment]
Makes sense! I assumed parallel would work mainly because the web interface uses it to create resourcees, and I've never waited for a server to spin up before creating another one.

**Comment by lyptt** [comment]
FWIW I think Scaleway was just being a bit slow yesterday, as server creation didn't take nearly as long this morning. Still, speedups are always nice if possible!

**Comment by sieben** [comment]
I think server creation could be done in an async manner. You can send the requests concurrently for server creation. The API does not support notifications at the moment so you would have to pull on the client side whether or not your server is now up. I guess it adds more complexity to the client-side code.
