### ISSUE TITLE
Handle instances out of stock more gracefully?

### ISSUE THREAD

**Issue by mtarnovan** [terraform-providers/terraform-provider-scaleway#66]
Hi,

I'm seeing some weird behaviour which I think originates from certain instance types being out of stock at scw. When trying to provision an out of stock type of instance it will hang indefinitely with `Still creating...`. 

Looking at the scaleway api docs, I see the only documented response is a 201 for a successful creation, so I guess this needs some fixing upstream in the scw api before it can be implemented in the terraform provider.

This issue might also be relevant: https://github.com/scaleway/api.scaleway.com/issues/46 

Thanks,

Mihai

**Comment by nicolai86** [comment]
@mtarnovan it might be possible to address this by checking availability first. I’ll look into it and update the issue once I know more.

Thanks!

**Comment by nicolai86** [comment]
@mtarnovan this will be part of the next release - v1.4.2 or v1.5.0

**Comment by mtarnovan** [comment]
@nicolai86 was this released already? thanks.

**Comment by nicolai86** [comment]
Yes, as part of 1.5.0 

https://releases.hashicorp.com/terraform-provider-scaleway/1.5.0/
