### ISSUE TITLE
SCALEWAY_ORGANIZATION is not the Token Access Key

### ISSUE THREAD

**Issue by deurk** [terraform-providers/terraform-provider-scaleway#67]
The documentation (https://www.terraform.io/docs/providers/scaleway/) states that to use the provider, one needs to set the environment variable `SCALEWAY_ORGANIZATION` to the Token Access Key. This is incorrect as it returns the following error when trying to use it:

`StatusCode: 400, Type: invalid_request_error, APIMessage: Validation Error, Details: map[organization:[<MY_SCALEWAY_TOKEN_ACCESS_KEY> is not a valid UUID.]]`

One actually needs to retrieve the UUID to use as the correct `SCALEWAY_ORGANIZATION` environment variable using the following command: 

`curl https://account.scaleway.com/organizations -H "X-Auth-Token: <TOKEN_SECRET_KEY>"`

The request will return a JSON result in which you will find the `id` within `organizations` to use.

**Comment by nicolai86** [comment]
fixed in #75
