### ISSUE TITLE
[Enhancement] Automatically create required volumes

### ISSUE THREAD

**Issue by dcharbonnier** [terraform-providers/terraform-provider-scaleway#99]
The required volumes should be automatically created, for example a START-1L need to start with a 150Go l_ssd volume, it's not an option or you will get a  :
> * scaleway_server.runner: StatusCode: 400, Type: invalid_request_error, APIMessage: The total volume size of START1-L instances must be equal to 200GB

**Comment by nicolai86** [comment]
Thank you @dcharbonnier for suggesting this. 

Terraform is managing infrastructure and as a user of the Terraform Scaleway provider I would find it very confusing if Terraform created more resources than I asked it to. It also opens up a bunch of questions related to how to use and reference said volume, life cycle management and more. 

I strongly believe this limitation should be lifted by Scaleway itself. 

That being said maybe there's a way to allow users to opt into this behaviour, e.g. 

```
resource "scaleway_server" "with_volume" {
  create_required_volumes = true
  ...
}
```

What do you think?

**Comment by dcharbonnier** [comment]
Yes I think this should be fine, the problem otherwise is that you can't switch easily from one type of server to an other one. Even if it's useful to be able to manage the volumes I think most of the time people using terraform create and destroy machines with their volumes. I personally consiter a machine with the volumes and if I destroy one I destroy the other too.

**Comment by Sh4d1** [comment]
@nicolai86 @dcharbonnier you don't need it anymore :smile: When you create an instance with no volumes, it will now adapt automatically to the wanted size

**Comment by QuentinBrosse** [comment]
Hi @dcharbonnier and thank for your proposal.
Please migrate to the new [scaleway_instance_server](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html) resource. If you leave the `root_volume` attribute empty, a default volume will be automatically created for your server. :)
Our [migration guide](https://www.terraform.io/docs/providers/scaleway/guides/migration_guide_v2.html) will help you. Feel free to reopen the issue if you need more help. :)
